---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-qarec
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx-qarec
    app.kubernetes.io/part-of: ingress-nginx-qarec
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 31081
    - port: 443
      targetPort: 443
      nodePort: 31444
      name: https
  selector:
    app.kubernetes.io/name: ingress-nginx-qarec
    app.kubernetes.io/part-of: ingress-nginx-qarec
  type: NodePort
#  clusterIP: 10.96.25.183
